//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.PrograAvanzada.Vite.Model
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract] public partial class PERSONA_REPORTANDO_EXTRAVIO
    {
        [DataMember] public int ID { get; set; }
        [DataMember] public Nullable<int> ID_PERSONA { get; set; }
        [DataMember] public Nullable<int> ID_CATEGORIA { get; set; }
        [DataMember] public Nullable<System.DateTime> FECHA_REPORTE { get; set; }
    
        public virtual CATEGORIA_ARTICULO CATEGORIA_ARTICULO { get; set; }
        public virtual PERSONA PERSONA { get; set; }
    }
}
